### ISSUE TITLE
Websocket port change

### ISSUE THREAD

**Issue by dementedmonkey** [neilenns/Collins-FMS-3000-Display#1]
The port 8081 used by the websocket was used by PilotEdge, and was causing conflicts.   In the 0.2.0 version of the mod, I switched this to use 8086 (and fixed another bug).   You'll probably want to update your default websocket port to 8086 for the newer mod version.

**Comment by neilenns** [comment]
Thanks for the heads up @dementedmonkey! I pushed the update and will cut a new release in a bit. This is a good excuse for me to get automated release builds done with github actions :)
