### ISSUE TITLE
App icon has disappeared?

### ISSUE THREAD

**Issue by neilenns** [neilenns/Collins-FMS-3000-Display#21]
There used to be an app icon in the task bar but now it's just a file icon 🤔 Start menu is ok though?

**Comment by tigert** [comment]
![image](https://user-images.githubusercontent.com/2587818/206879110-b34ce08d-6e92-4919-93f6-ba267c403db5.png)
 
works for me..?

**Comment by neilenns** [comment]
Yeah a reboot of my PC fixed it. Woo!
